apiVersion: batch/v1
kind: Job
metadata:
  name: maptiles
spec:
  template:
    metadata:
      name: maptiles
    spec:
      containers:
      - name: maptiles
        image: evfirerob/maptiles:latest
        command: ["/bin/bash"]
        args: ["-c", "./run-pipeline.sh"]
        env:
        - name: PROJECT
          value: mlab-sandbox
      restartPolicy: Never
      nodeSelector:
        stats-pipeline-node: "true"
  backoffLimit: 1
  ttlSecondsAfterFinished: 0